version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
     orbs:
       sonarqube: clicklogiq/sonarqube@0.0.2

#       - run:
#           name: Analyze on SonarCloud
#           command: mvn verify sonar:sonar
# workflows:
#   main:
#     jobs:
#       - build:
#           context: SonarCloud
