version: 2.1
orbs:
  sonarqube: clicklogiq/sonarqube@0.0.2
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on sonarqube
          command: mvn verify sonar:sonar
# workflows:
#   main:
#     jobs:
#       - build:
#           context: SonarCloud

